package com.example.springapp.model;

public enum Citizenship {
    AFGHANISTAN, ALBANIA, ALGERIA, AMERICAN_SAMOA, ANDORRA, ANGOLA, ARGENTINA, ARMENIA, AUSTRALIA, AUSTRIA, AZERBAIJAN, THE_BAHAMAS, BAHRAIN,
    BANGLADESH, BARBADOS, BELARUS, BELGIUM, BELIZE, BENIN, BERMUDA, BHUTAN, BOLIVIA, BOSNIA_AND_HERZEGOVINA, BOTSWANA, BRAZIL, BRITISH_VIRGIN_ISLANDS,
    BRUNEI, BULGARIA, BURUNDI, CAMBODIA, CAMEROON, CANADA, CAYMAN_ISLANDS, CENTRAL_AFRICAN_REPUBLIC, CHAD, CHILE, CHINA, CHRISTMAS_ISLAND,
    COCOS_ISLANDS, COLOMBIA, DEMOCRATIC_REPUBLIC_OF_CONGO, COSTA_RICA, CROATIA, CUBA, CYPRUS, CZECHIA, DENMARK, DOMINICAN_REPUBLIC,
    ECUADOR, EGYPT, EQUATORIAL_GUINEA, ESTONIA, ETHIOPIA, FIJI, FINLAND, FRANCE, GABON, THE_GAMBIA, GEORGIA, GERMANY, GHANA, GIBRALTAR,
    GREECE, GREENLAND, GRENADA, GUAM, GUATEMALA, HAITI, HONDURAS, HONG_KONG, HUNGARY, ICELAND, INDIA, INDONESIA, IRAN, IRAQ, IRELAND,
    ISRAEL, ITALY, JAMAICA, JAPAN, JORDAN, KAZAKHSTAN, KENYA, KIRIBATI, NORTH_KOREA, SOUTH_KOREA, KOSOVO, KUWAIT, KYRGYZSTAN, LAOS,
    LATVIA, LEBANON, LIBERIA, LIBYA, LIECHTENSTEIN, LITHUANIA, LUXEMBOURG, MADAGASCAR, MALAWI, MALAYSIA, MALDIVES, MALI, MALTA, MARSHALL_ISLANDS,
    MAURITANIA, MAURITIUS, MEXICO, MOLDOVA, MONACO, MONGOLIA, MONTENEGRO, MOROCCO, MOZAMBIQUE, NAMIBIA, NEPAL, NETHERLANDS, NEW_ZEALAND,
    NICARAGUA, NIGER, NIGERIA, NORTH_MACEDONIA, NORWAY, OMAN, PAKISTAN, PALAU, PANAMA, PAPUA_NEW_GUINEA, PARAGUAY, PERU, PHILIPPINES,
    POLAND, PORTUGAL, PUERTO_RICO, QATAR, ROMANIA, RUSSIA, SAINT_LUCIA, SAINT_MARTIN, SAINT_VINCENT_AND_GRENADINES, SAMOA, SAN_MARINO,
    SAUDI_ARABIA, SENEGAL, SERBIA, SEYCHELLES, SIERRA_LEONE, SINGAPORE, SLOVAKIA, SLOVENIA, SOLOMON_ISLANDS, SOUTH_AFRICA, SOUTH_SUDAN,
    SPAIN, SRI_LANKA, SUDAN, SURINAME, SWEDEN, SWITZERLAND, SYRIA, TAIWAN, TAJIKISTAN, TANZANIA, THAILAND, TOGO, TONGA, TUNISIA, TURKEY,
    TURKMENISTAN, TUVALU, UGANDA, UKRAINE, UNITED_ARAB_EMIRATES, UNITED_KINGDOM, UNITED_STATES, URUGUAY, UZBEKISTAN, VENEZUELA, VIETNAM,
    YEMEN, ZAMBIA, ZIMBABWE
}
